console.log("*******************************************");
let schName="=>Masai School";
console.log("School name",schName);
console.log("-------------------------------------------");
console.log();
let stName="Praveen Singh";
let grdSec="7A";
let rollNo=11;
console.log("student Name Grad Roll Number");
console.log(stName,grdSec,rollNo);
console.log("-------------------------------------------");
let physics=95;
let chemistry=90;
let maths=98;
console.log("Marks in Physics out of 100 =>",physics);
console.log("Marks in Chemistry out of 100 =>",chemistry);
console.log("Marks in Maths out of 100 =>",maths);
console.log();
console.log("*******************************************");
